#!/bin/bash
set -o errexit
set -o nounset
set -o xtrace

script_dir="$( dirname "${0}" )"

source "${script_dir}/../config/targets.sh"
source "${script_dir}/../config/release.sh"
source "${script_dir}/../config/functions.sh"

for target in ${targets}
do
	sub_target_list="subtarget_${target}"
	for sub_target in ${!sub_target_list}
	do
		image_name="$( get_docker_image_tag "${IMAGE_NAME}" "${target}" "${sub_target}" )" 
                cache_image_name="$( get_docker_image_tag "${DOCKER_REPO}:${CACHE_TAG}" "${target}" "${sub_target}" )"
                latest_image_name="$( get_docker_image_tag "${DOCKER_REPO}:latest" "${target}" "${sub_target}" )"

		echo "Pulling previously built cache: ${cache_image_name}, ${latest_image_name}"
		docker image pull "${latest_image_name}" || true
		docker image pull "${cache_image_name}" || true

		docker build \
                        --cache-from "${cache_image_name}" \
                        --cache-from "${latest_image_name}" \
			--build-arg "OPENWRT_RELEASE=${release}" \
			--build-arg "OPENWRT_SUBTARGET=${sub_target}" \
			--build-arg "OPENWRT_TARGET=${target}" \
			--build-arg "VCS_REF=${SOURCE_COMMIT}" \
			--tag "${image_name}" --file "${DOCKERFILE_PATH}" .
	done
done
